#
# Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
#

authentication:
  type: PROP_FILE

fileAuth:
  users:
    -
      username: "{{ ts_user }}"
      password: "{{ ts_pw }}"

repository:
  host: 0.0.0.0
  port: 2036
  numberOfWorkers: "{{ ts_workers }}"
  # Minutes to invalidate and close the unused indexes for tasks
  # Default is 4 hours, setting it to 0 means infinite (turns the feature off)
  # indexTimeout: 240

  database:
    type: b2i_mysql
    datasource: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    driver: com.mysql.jdbc.Driver
    scheme: jdbc:mysql://
    location: "{{ ts_snowowl_db_host }}"
    settings: ?useServerPrepStmts=true&useCursorFetch=true
    username: "{{ ts_snowowl_db_user }}"
    password: "{{ ts_snowowl_db_password }}"

snomed:
  ids:
    strategy : CIS
    cisBaseUrl : "{{ ts_cis_url }}"
    cisContextRoot : api
    cisUserName : "{{ ts_cis_username }}"
    cisPassword : "{{ ts_cis_password }}"
    cisClientSoftwareKey : "{{ ts_cis_client_name }}"
    cisNumberOfPollTries : 240
    cisTimeBetweenPollTries : 500
    enforceNamespace: INT
  maxReasonerCount: 1
  maxReasonerRuns: 100000
reviewManager:
  # Minutes to keep reviews in CURRENT state persisted in the index (default 15 minutes)
  keepCurrentMins: 120
  # Minutes to keep reviews in others states persisted (default 5 minutes)
  keepOtherMins: 120

# metrics:
  # Enable Request execution metrics logging
  # enabled: true | false
